name: Release

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  release-please:
    permissions:
      contents: write  # for google-github-actions/release-please-action to create release commit
      pull-requests: write  # for google-github-actions/release-please-action to create release PR
    runs-on: ubuntu-latest
    outputs:
      package1_release_created: ${{ steps.release.outputs.package1--release_created }}
      package1_tag_name: ${{ steps.release.outputs.package1--tag_name }}
      package2_release_created: ${{ steps.release.outputs.package2--release_created }}
      package2_tag_name: ${{ steps.release.outputs.package2--tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        id: release
        with:
          include-component-in-tag: true
          token: ${{ secrets.PAT }}